// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAheQGqo5vai6Ivlvoo5Zki3sjKx8309QQ',
    appId: '1:723393638531:web:3ef0d7e891687ac7e02bb6',
    messagingSenderId: '723393638531',
    projectId: 'vrittanta-fe68c',
    authDomain: 'vrittanta-fe68c.firebaseapp.com',
    storageBucket: 'vrittanta-fe68c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTAWk2k4pw2JBP87LaPZdKNt172RdxQY4',
    appId: '1:723393638531:android:defb86947b225df9e02bb6',
    messagingSenderId: '723393638531',
    projectId: 'vrittanta-fe68c',
    storageBucket: 'vrittanta-fe68c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC178BGvMPN4vpmGRfh3oTOIeP44vEJ6DM',
    appId: '1:723393638531:ios:e5de6d9b31b11bafe02bb6',
    messagingSenderId: '723393638531',
    projectId: 'vrittanta-fe68c',
    storageBucket: 'vrittanta-fe68c.firebasestorage.app',
    iosClientId: '723393638531-krgjqbohjrbpaeuok1mqm9hqcknaorq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.vrittanta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC178BGvMPN4vpmGRfh3oTOIeP44vEJ6DM',
    appId: '1:723393638531:ios:e5de6d9b31b11bafe02bb6',
    messagingSenderId: '723393638531',
    projectId: 'vrittanta-fe68c',
    storageBucket: 'vrittanta-fe68c.firebasestorage.app',
    iosClientId: '723393638531-krgjqbohjrbpaeuok1mqm9hqcknaorq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.vrittanta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAheQGqo5vai6Ivlvoo5Zki3sjKx8309QQ',
    appId: '1:723393638531:web:d4ccb05108a66170e02bb6',
    messagingSenderId: '723393638531',
    projectId: 'vrittanta-fe68c',
    authDomain: 'vrittanta-fe68c.firebaseapp.com',
    storageBucket: 'vrittanta-fe68c.firebasestorage.app',
  );
}
